[package]
name = "srml-authorship"
version = "0.1.0"
description = "Block and Uncle Author tracking for the SRML"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives",  path = "../../core/primitives", default-features = false }
parity-scale-codec = { path = "/home/thiolliere/Developpement/parity-scale-codec", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
srml-support = { path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
runtime_io = { package = "sr-io", path = "../../core/sr-io", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"primitives/std",
	"sr-primitives/std",
	"rstd/std",
	"srml-support/std",
	"system/std",
	"runtime_io/std",
]
