[package]
name = "substrate-consensus-common-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Common consensus primitives"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.2", default-features = false, path = "/home/thiolliere/Developpement/parity-scale-codec" }
client = { package = "substrate-client", path = "../../../client", default-features = false }
sr-primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }

[features]
default = ["std"]
std = [
    "rstd/std",
    "client/std",
    "codec/std",
    "sr-primitives/std"
]
