[package]
name = "substrate-consensus-aura-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
parity-scale-codec = { path = "/home/thiolliere/Developpement/parity-scale-codec", default-features = false }
substrate-client = { path = "../../../client", default-features = false }
substrate-primitives = { path = "../../../primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }

[features]
default = ["std"]
std = [
	"rstd/std",
	"parity-scale-codec/std",
	"runtime_primitives/std",
	"substrate-client/std",
	"substrate-primitives/std",
]
